### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by lgwapnitsky** [pawkakol1/worlds-air-quality-index#18]
How do I change the update frequency? The last time mine updated was about eight hours ago

**Comment by lichenophile** [comment]
Same issue here

**Comment by pawkakol1** [comment]
The update frequency is fixed, and it is 30 min, the **_throttle_** is used to manage the update frequency

**Comment by pawkakol1** [comment]
Do you want to change it manual?

**Comment by mtgpcs** [comment]
How can we tell if the update is working? Mine shows 1 hour since the last update. 
![image](https://user-images.githubusercontent.com/67062341/220041274-7c6eec05-ad5c-4084-b2b1-401a0ce3bc90.png)

**Comment by pawkakol1** [comment]
Not exactly @mtgpcs. This means the entity changed value about 1 hour ago.
If you would mouse over on "1 hour ago" like below, you can see when value was updated, and when it was changed:
![image](https://user-images.githubusercontent.com/69692263/221682611-4525703b-68b8-4395-bf15-762244585a3b.png)
Additionally I put info about waqi server's value updating as the "LastUpdate" attribute of entity.
Even if anybody would increase polling frequency it wouldn't change anything, because waqi server updates its values every hour.
