### ISSUE TITLE
Air Quality Index entity unavailable

### ISSUE THREAD

**Issue by maga80** [pawkakol1/worlds-air-quality-index#30]
Hi Alter upgrade to 0.3.4 entity Air Quality Index is unavailable

**Comment by Norbator** [comment]
@pawkakol1 : in release version 0.3.3 WorldsAirQualityIndexSensor.update function had a local variable called _data 
In release version 0.3.4 you replaced it with the object property self._data (which is imho a better design) without updating the rest of code. 

Since you already made the correction as seen in your github source code, could you please release a new version of your integration?

**Comment by yvh65** [comment]
Version 0.3.4 is useless without AQI index.

**Comment by pawkakol1** [comment]
@Norbator, @yvh65, @maga80 
Could you try with 0.3.5, I withdrawn 0.3.4, there was pre-release version 0.3.5-beta1, and I just moved it to 0.3.5 last release version.
For the future, you can install pre-release version by opening the integration, clicking on settings, and choosing "Redownload" option - there will be shown popup window like below, and you just need to slide right the "Show beta versions" button
![image](https://user-images.githubusercontent.com/69692263/198342050-b90ff2ae-2a41-4688-b774-ce2a1f9983a9.png)

Sorry for that delay, but I had stuffs to do.

**Comment by maga80** [comment]
Hi 0.3.5 is running without issue.  Thnx a lot

**Comment by yvh65** [comment]
Thanx for good work!
