### ISSUE TITLE
Unable to delete a location

### ISSUE THREAD

**Issue by yvansandoz** [pawkakol1/worlds-air-quality-index#32]
I would like to remove a location, but cannot figure out how to do it.

**Comment by pawkakol1** [comment]
I'm not sure if, you said all, what you want to achive, but you can just delete existed station (integration), and add integration again, and choose "station ID" option instead "Geolocalization".
You need to ensure if you have updated the version, because it wasn't able to add using station ID on firsts versions

**Comment by pawkakol1** [comment]
Due to lack of respond, I close the issue
